// The two things an owner does with a report: print it, or send the gist to
// someone on WhatsApp. Both read the same aggregated ReportData.

import { countryByCode } from './countries';
import { highlightsOf, type ReportData } from './reporting';
import type { Lang } from './types';

const SLOGAN: Record<Lang, string> = {
  en: 'Your business. One system.',
  sw: 'Biashara yako. Mfumo mmoja.',
};

const T = {
  en: {
    title: 'COMPREHENSIVE FINANCIAL REPORT', period: 'Period', summary: 'Executive summary',
    sales: 'Total sales', profit: 'Total profit', cashMobile: 'Cash & mobile', sessionExp: 'Session expenses',
    purchases: 'Purchases', otherExp: 'Other expenses', staffDebts: 'Staff debts', losses: 'Losses',
    banked: 'Amount banked', balance: 'Balance difference',
    daily: 'Daily breakdown', date: 'Date', cash: 'Cash', mobile: 'Mobile', sExp: 'S.Exp', sPur: 'S.Purch',
    oExp: 'O.Exp', sDebt: 'S.Debt', total: 'TOTAL',
    lossesTable: 'Losses & damages', topExpenses: 'Top expenses', description: 'Description', amount: 'Amount',
    highlights: 'Key highlights', bestDay: 'Best sales day', avgProfit: 'Avg daily profit', margin: 'Profit margin',
    footer: 'Generated by Bermi One', noData: 'No verified closings in this period.',
  },
  sw: {
    title: 'RIPOTI KAMILI YA FEDHA', period: 'Kipindi', summary: 'Muhtasari',
    sales: 'Jumla ya mauzo', profit: 'Jumla ya faida', cashMobile: 'Taslimu na simu', sessionExp: 'Matumizi ya siku',
    purchases: 'Manunuzi', otherExp: 'Matumizi mengine', staffDebts: 'Madeni ya wafanyakazi', losses: 'Hasara',
    banked: 'Zilizopelekwa benki', balance: 'Tofauti',
    daily: 'Uchambuzi wa kila siku', date: 'Tarehe', cash: 'Taslimu', mobile: 'Simu', sExp: 'Mat.', sPur: 'Man.',
    oExp: 'Meng.', sDebt: 'Deni', total: 'JUMLA',
    lossesTable: 'Hasara na uharibifu', topExpenses: 'Matumizi makubwa', description: 'Maelezo', amount: 'Kiasi',
    highlights: 'Mambo muhimu', bestDay: 'Siku bora ya mauzo', avgProfit: 'Wastani wa faida', margin: 'Kiwango cha faida',
    footer: 'Imetengenezwa na Bermi One', noData: 'Hakuna kufunga kulikothibitishwa kipindi hiki.',
  },
} as const;

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function buildComprehensiveReportHtml(data: ReportData, lang: Lang): string {
  const L = T[lang];
  const sym = countryByCode(data.businesses[0]?.country_code || 'TZ').sym;
  const money = (n: number) => sym + ' ' + Math.round(n).toLocaleString('en-US');
  // Nothing recorded reads as a dash, not as a hard zero.
  const money0 = (n: number) => (Math.round(n) ? money(n) : '—');
  const names = data.businesses.map((b) => b.name).join(', ');
  const { totals, days } = data;
  const showDebts = totals.staffDebts > 0;
  const showBalance = Math.round(totals.balance) !== 0;

  const summaryCells: [string, string, string?][] = [
    [L.sales, money0(totals.sales)],
    [L.profit, money0(totals.profit), '#0a7a44'],
    [L.cashMobile, money0(totals.cash + totals.mobile)],
    [L.sessionExp, money0(totals.sessionExpenses)],
    [L.purchases, money0(totals.sessionPurchases)],
    [L.otherExp, money0(totals.otherExpenses)],
    ...(showDebts ? ([[L.staffDebts, money0(totals.staffDebts), '#9a6b00']] as [string, string, string?][]) : []),
    [L.losses, money0(totals.losses), totals.losses > 0 ? '#b3261e' : undefined],
    [L.banked, money0(totals.banked), '#4b3fd6'],
    ...(showBalance ? ([[L.balance, money0(totals.balance), '#b3261e']] as [string, string, string?][]) : []),
  ];

  const dayRows = days
    .map((d) => `<tr>
      <td>${d.date}</td>
      <td class="n b">${money0(d.sales)}</td>
      <td class="n" style="color:#0a7a44">${money0(d.profit)}</td>
      <td class="n">${money0(d.cash)}</td>
      <td class="n">${money0(d.mobile)}</td>
      <td class="n">${money0(d.sessionExpenses)}</td>
      <td class="n">${money0(d.sessionPurchases)}</td>
      <td class="n">${money0(d.otherExpenses)}</td>
      ${showDebts ? `<td class="n">${money0(d.staffDebts)}</td>` : ''}
      <td class="n">${money0(d.losses)}</td>
      <td class="n" style="color:#4b3fd6">${money0(d.banked)}</td>
      ${showBalance ? `<td class="n" style="color:${Math.round(d.balance) === 0 ? '#0a7a44' : '#b3261e'}">${money0(d.balance)}</td>` : ''}
    </tr>`)
    .join('');

  const totalRow = `<tr class="tot">
    <td>${L.total}</td>
    <td class="n">${money0(totals.sales)}</td>
    <td class="n">${money0(totals.profit)}</td>
    <td class="n">${money0(totals.cash)}</td>
    <td class="n">${money0(totals.mobile)}</td>
    <td class="n">${money0(totals.sessionExpenses)}</td>
    <td class="n">${money0(totals.sessionPurchases)}</td>
    <td class="n">${money0(totals.otherExpenses)}</td>
    ${showDebts ? `<td class="n">${money0(totals.staffDebts)}</td>` : ''}
    <td class="n">${money0(totals.losses)}</td>
    <td class="n">${money0(totals.banked)}</td>
    ${showBalance ? `<td class="n">${money0(totals.balance)}</td>` : ''}
  </tr>`;

  const breakdownTable = (title: string, rows: { label: string; amount: number }[]) =>
    rows.length
      ? `<h2>${title}</h2>
        <table>
          <thead><tr><th class="l">${L.description}</th><th>${L.amount}</th></tr></thead>
          <tbody>${rows.map((r) => `<tr><td>${esc(r.label)}</td><td class="n b">${money0(r.amount)}</td></tr>`).join('')}</tbody>
        </table>`
      : '';

  const h = highlightsOf(data);

  return `<!doctype html>
<html lang="${lang}">
<head>
<meta charset="utf-8" />
<title>${esc(names)} — ${L.title}</title>
<style>
  @page { size: A4 landscape; margin: 10mm; }
  * { box-sizing: border-box; }
  body { font-family: "Helvetica Neue", Arial, sans-serif; color: #111; margin: 0; font-size: 10px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #111; padding-bottom: 8px; margin-bottom: 10px; }
  .biz { font-size: 17px; font-weight: 800; letter-spacing: -0.2px; }
  .city { font-size: 10px; color: #555; margin-top: 2px; }
  .sheet { font-size: 12px; font-weight: 700; text-align: right; letter-spacing: 0.5px; }
  h2 { font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.6px; margin: 14px 0 5px; color: #333; }
  .grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 6px; }
  .kpi { border: 1px solid #ccc; border-radius: 4px; padding: 7px 9px; }
  .kpi .k { font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.3px; color: #666; font-weight: 700; }
  .kpi .v { font-size: 13px; font-weight: 800; margin-top: 3px; font-variant-numeric: tabular-nums; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #bbb; padding: 3px 5px; }
  thead th { background: #f0f0f2; font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.3px; text-align: right; padding: 5px 4px; }
  thead th.l { text-align: left; }
  td.n { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
  td.b { font-weight: 700; }
  tr.tot td { background: #e8e8ee; font-weight: 800; }
  .two { display: flex; gap: 14px; align-items: flex-start; }
  .two > div { flex: 1; }
  .hl { display: flex; gap: 18px; font-size: 10px; color: #333; margin-top: 4px; }
  .hl strong { font-size: 11.5px; }
  .foot { margin-top: 14px; border-top: 1px solid #ccc; padding-top: 6px; display: flex; justify-content: space-between; font-size: 9px; color: #777; }
  tr { page-break-inside: avoid; }
  @media print { .noprint { display: none; } }
  .noprint { margin-bottom: 12px; }
  .noprint button { font: inherit; font-weight: 700; padding: 8px 16px; border-radius: 8px; border: 1px solid #444; background: #111; color: #fff; cursor: pointer; }
</style>
</head>
<body>
  <div class="noprint"><button onclick="window.print()">Print / Save as PDF</button></div>

  <div class="head">
    <div>
      <div class="biz">${esc(names)}</div>
      <div class="city">${L.period}: ${data.from} → ${data.to}</div>
    </div>
    <div class="sheet">${L.title}</div>
  </div>

  ${days.length === 0 ? `<p style="color:#888">${L.noData}</p>` : `
  <h2>${L.summary}</h2>
  <div class="grid">
    ${summaryCells.map(([k, v, c]) => `<div class="kpi"><div class="k">${k}</div><div class="v"${c ? ` style="color:${c}"` : ''}>${v}</div></div>`).join('')}
  </div>

  <h2>${L.highlights}</h2>
  <div class="hl">
    <div>${L.bestDay}: <strong>${h.bestDay ? `${h.bestDay.date} — ${money(h.bestDay.sales)}` : '—'}</strong></div>
    <div>${L.avgProfit}: <strong>${money(h.avgDailyProfit)}</strong></div>
    <div>${L.margin}: <strong>${h.profitMargin}%</strong></div>
  </div>

  <h2>${L.daily}</h2>
  <table>
    <thead>
      <tr>
        <th class="l">${L.date}</th><th>${L.sales}</th><th>${L.profit}</th><th>${L.cash}</th><th>${L.mobile}</th>
        <th>${L.sExp}</th><th>${L.sPur}</th><th>${L.oExp}</th>${showDebts ? `<th>${L.sDebt}</th>` : ''}
        <th>${L.losses}</th><th>${L.banked}</th>${showBalance ? `<th>${L.balance}</th>` : ''}
      </tr>
    </thead>
    <tbody>${dayRows}${totalRow}</tbody>
  </table>

  <div class="two">
    <div>${breakdownTable(L.lossesTable, data.lossBreakdown)}</div>
    <div>${breakdownTable(L.topExpenses, data.expenseBreakdown.slice(0, 10))}</div>
  </div>
  `}

  <div class="foot">
    <span>${L.footer} — ${SLOGAN[lang]}</span>
    <span>${esc(names)} · ${data.from} → ${data.to}</span>
  </div>
</body>
</html>`;
}

export function openComprehensiveReport(data: ReportData, lang: Lang): boolean {
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(buildComprehensiveReportHtml(data, lang));
  w.document.close();
  return true;
}

/** WhatsApp-flavoured plain text — *bold* markers, no HTML. */
export function buildWhatsappSummary(data: ReportData, lang: Lang, money: (n: number) => string): string {
  const L = T[lang];
  const { totals } = data;
  const h = highlightsOf(data);
  const names = data.businesses.map((b) => b.name).join(', ');
  const out: string[] = [];

  out.push(`*${names}*`);
  out.push(`${L.period}: ${data.from} → ${data.to}`);
  out.push('');
  out.push(`*${L.summary}*`);
  out.push(`${L.sales}: ${money(totals.sales)}`);
  out.push(`${L.profit}: ${money(totals.profit)}`);
  out.push(`${L.cash}: ${money(totals.cash)}`);
  out.push(`${L.mobile}: ${money(totals.mobile)}`);
  out.push(`${L.sessionExp}: ${money(totals.sessionExpenses)}`);
  out.push(`${L.purchases}: ${money(totals.sessionPurchases)}`);
  out.push(`${L.otherExp}: ${money(totals.otherExpenses)}`);
  if (totals.staffDebts > 0) out.push(`${L.staffDebts}: ${money(totals.staffDebts)}`);
  out.push(`${L.losses}: ${money(totals.losses)}`);
  out.push(`${L.banked}: ${money(totals.banked)}`);
  if (Math.round(totals.balance) !== 0) out.push(`${L.balance}: ${money(totals.balance)}`);

  out.push('');
  out.push(`*${L.highlights}*`);
  out.push(`${L.bestDay}: ${h.bestDay ? `${h.bestDay.date} — ${money(h.bestDay.sales)}` : '—'}`);
  out.push(`${L.avgProfit}: ${money(h.avgDailyProfit)}`);
  out.push(`${L.margin}: ${h.profitMargin}%`);

  if (data.lossBreakdown.length) {
    out.push('');
    out.push(`*${L.lossesTable}*`);
    for (const r of data.lossBreakdown.slice(0, 3)) out.push(`• ${r.label}: ${money(r.amount)}`);
  }
  if (data.expenseBreakdown.length) {
    out.push('');
    out.push(`*${L.topExpenses}*`);
    for (const r of data.expenseBreakdown.slice(0, 3)) out.push(`• ${r.label}: ${money(r.amount)}`);
  }

  out.push('');
  out.push(`_${L.footer}_`);
  return out.join('\n');
}

export function openWhatsapp(text: string, phone?: string): void {
  const target = phone?.replace(/[^0-9]/g, '');
  const base = target ? `https://wa.me/${target}` : 'https://wa.me/';
  window.open(`${base}?text=${encodeURIComponent(text)}`, '_blank');
}
