// The filled-in counterpart to the blank stock sheet: one closed day, printed
// as a record. Same paper language as stockSheet.ts so a bar can file the
// blank sheet and the signed-off report side by side.

import { closingItemsTotal, groupByCategory, soldOf } from './calc';
import type { Business, ClosingItemKind, Lang, Product, StockSession } from './types';
import { countryByCode } from './countries';

const SLOGAN: Record<Lang, string> = {
  en: 'Your business. One system.',
  sw: 'Biashara yako. Mfumo mmoja.',
};

const T = {
  en: {
    title: 'DAILY CLOSING REPORT', item: 'Item', opening: 'Opening', added: 'Added', total: 'Total',
    closing: 'Closing', sold: 'Sold', price: 'Price', amount: 'Sales', profit: 'Profit',
    subtotal: 'Subtotal', grand: 'TOTAL', summary: 'Summary', expectedSales: 'Expected sales',
    grossProfit: 'Gross profit', cash: 'Cash', mobile: 'Mobile money', bank: 'Bank', difference: 'Difference',
    deductions: 'Expenses, losses & staff debt', expense: 'Expense', loss: 'Loss / breakage', debt: 'Staff debt',
    reason: 'Reason given', note: 'Note', ownerComments: 'Owner comments',
    submittedBy: 'Submitted by', approvedBy: 'Verified by', footer: 'Generated by Bermi One',
    statusOpen: 'OPEN', statusSubmitted: 'AWAITING VERIFICATION', statusApproved: 'VERIFIED & LOCKED',
    matched: 'Everything matches', short: 'Cash short', over: 'More than expected', none: 'None recorded',
  },
  sw: {
    title: 'RIPOTI YA KUFUNGA SIKU', item: 'Bidhaa', opening: 'Mwanzo', added: 'Imeongezwa', total: 'Jumla',
    closing: 'Zilizobaki', sold: 'Zimeuzwa', price: 'Bei', amount: 'Mauzo', profit: 'Faida',
    subtotal: 'Jumla ndogo', grand: 'JUMLA', summary: 'Muhtasari', expectedSales: 'Mauzo yanayotarajiwa',
    grossProfit: 'Faida ghafi', cash: 'Taslimu', mobile: 'Simu', bank: 'Benki', difference: 'Tofauti',
    deductions: 'Matumizi, hasara na madeni', expense: 'Matumizi', loss: 'Hasara', debt: 'Deni la mfanyakazi',
    reason: 'Sababu', note: 'Maelezo', ownerComments: 'Maoni ya mmiliki',
    submittedBy: 'Amewasilisha', approvedBy: 'Amethibitisha', footer: 'Imetengenezwa na Bermi One',
    statusOpen: 'WAZI', statusSubmitted: 'INASUBIRI UTHIBITISHO', statusApproved: 'IMETHIBITISHWA',
    matched: 'Kila kitu kinalingana', short: 'Fedha pungufu', over: 'Zaidi ya ilivyotarajiwa', none: 'Hakuna',
  },
} as const;

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function buildSessionReportHtml(opts: {
  business: Business;
  products: Product[];
  session: StockSession;
  lang: Lang;
}): string {
  const { business, products, session, lang } = opts;
  const L = T[lang];
  const sym = countryByCode(business.country_code || 'TZ').sym;
  const money = (n: number) => sym + ' ' + Math.round(n).toLocaleString('en-US');
  const counts = session.counts || {};

  // Only lines that were actually counted belong on the record.
  const counted = products.filter((p) => counts[p.id] !== undefined);
  const groups = groupByCategory(counted);

  const expected = counted.reduce((s, p) => s + soldOf(p, counts) * p.price, 0);
  const gross = counted.reduce((s, p) => s + soldOf(p, counts) * p.profit, 0);
  const deductions = closingItemsTotal(session);
  const received = Number(session.cash || 0) + Number(session.mobile || 0) + Number(session.bank_in || 0) + deductions;
  const diff = expected - received;

  const statusLabel = session.status === 'verified' ? L.statusApproved : session.status === 'submitted' ? L.statusSubmitted : L.statusOpen;
  const statusColor = session.status === 'verified' ? '#0a7a44' : session.status === 'submitted' ? '#9a6b00' : '#666';

  const body = groups
    .map((g) => {
      let catSales = 0;
      let catProfit = 0;
      const rows = g.items
        .map((p) => {
          const closing = Number(counts[p.id]);
          const avail = p.opening + p.added;
          const sold = soldOf(p, counts);
          const sales = sold * p.price;
          const prof = sold * p.profit;
          catSales += sales;
          catProfit += prof;
          return `<tr>
            <td class="item">${esc(p.name)}<span class="unit">${esc(p.unit)}</span></td>
            <td class="n">${p.opening}</td>
            <td class="n">${p.added}</td>
            <td class="n">${avail}</td>
            <td class="n">${closing}</td>
            <td class="n b">${sold}</td>
            <td class="n">${money(p.price)}</td>
            <td class="n b">${money(sales)}</td>
            <td class="n">${money(prof)}</td>
          </tr>`;
        })
        .join('');
      return `<tr class="cat"><td colspan="9">${esc(g.cat.toUpperCase())}</td></tr>
        ${rows}
        <tr class="sub"><td colspan="7">${L.subtotal} — ${esc(g.cat)}</td><td class="n">${money(catSales)}</td><td class="n">${money(catProfit)}</td></tr>`;
    })
    .join('');

  const kindLabel: Record<ClosingItemKind, string> = { expense: L.expense, loss: L.loss, debt: L.debt };
  const items = session.closing_items || [];
  const deductionRows = items.length
    ? items
        .map((i) => `<tr><td>${kindLabel[i.kind]}</td><td>${esc(i.note || '—')}</td><td class="n b">${money(i.amount)}</td></tr>`)
        .join('')
    : `<tr><td colspan="3" style="color:#888">${L.none}</td></tr>`;

  const summary: [string, string, string?][] = [
    [L.expectedSales, money(expected)],
    [L.cash, money(session.cash || 0)],
    [L.mobile, money(session.mobile || 0)],
    [L.bank, money(session.bank_in || 0)],
    [L.deductions, money(deductions)],
    [L.difference, money(Math.abs(diff)) + ' · ' + (diff === 0 ? L.matched : diff > 0 ? L.short : L.over), diff === 0 ? '#0a7a44' : '#b3261e'],
    [L.grossProfit, money(gross), '#0a7a44'],
  ];

  const dateStr = new Date(session.session_date).toLocaleDateString(lang === 'sw' ? 'sw-TZ' : 'en-GB', {
    weekday: 'short', day: '2-digit', month: 'short', year: 'numeric',
  });

  return `<!doctype html>
<html lang="${lang}">
<head>
<meta charset="utf-8" />
<title>${esc(business.name)} — ${L.title} ${session.session_date}</title>
<style>
  @page { size: A4 portrait; margin: 12mm 10mm; }
  * { box-sizing: border-box; }
  body { font-family: "Helvetica Neue", Arial, sans-serif; color: #111; margin: 0; font-size: 10px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #111; padding-bottom: 8px; margin-bottom: 4px; }
  .biz { font-size: 17px; font-weight: 800; letter-spacing: -0.2px; }
  .city { font-size: 10px; color: #555; margin-top: 2px; }
  .sheet { font-size: 12px; font-weight: 700; text-align: right; letter-spacing: 0.5px; }
  .status { display: inline-block; margin-top: 4px; font-size: 9px; font-weight: 800; letter-spacing: 0.6px; padding: 2px 7px; border-radius: 3px; border: 1px solid currentColor; }
  h2 { font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.6px; margin: 14px 0 5px; color: #333; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #bbb; padding: 3px 5px; }
  thead th { background: #f0f0f2; font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.3px; text-align: right; padding: 5px 4px; }
  thead th.l { text-align: left; }
  td.item { font-weight: 600; }
  td.item .unit { color: #777; font-weight: 400; font-size: 8.5px; margin-left: 5px; }
  td.n { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
  td.b { font-weight: 700; }
  tr.cat td { background: #e8e8ee; font-weight: 800; font-size: 9px; letter-spacing: 0.6px; padding: 4px 6px; }
  tr.sub td { background: #fafafa; font-size: 9px; font-weight: 700; text-align: right; color: #444; }
  .two { display: flex; gap: 14px; align-items: flex-start; }
  .two > div { flex: 1; }
  .sum th { text-align: left; background: #f7f7f9; font-weight: 700; }
  .sum td { text-align: right; font-weight: 700; font-variant-numeric: tabular-nums; }
  .who { margin-top: 12px; font-size: 9.5px; color: #555; display: flex; gap: 24px; }
  .note { margin-top: 10px; font-size: 9.5px; border-left: 3px solid #ccc; padding: 4px 0 4px 8px; color: #444; }
  .foot { margin-top: 14px; border-top: 1px solid #ccc; padding-top: 6px; display: flex; justify-content: space-between; font-size: 9px; color: #777; }
  tr { page-break-inside: avoid; }
  @media print { .noprint { display: none; } }
  .noprint { margin-bottom: 12px; }
  .noprint button { font: inherit; font-weight: 700; padding: 8px 16px; border-radius: 8px; border: 1px solid #444; background: #111; color: #fff; cursor: pointer; }
</style>
</head>
<body>
  <div class="noprint"><button onclick="window.print()">Print / Save as PDF</button></div>

  <div class="head">
    <div>
      <div class="biz">${esc(business.name)}</div>
      <div class="city">${esc([business.city, dateStr].filter(Boolean).join(' · '))}</div>
    </div>
    <div>
      <div class="sheet">${L.title}</div>
      <div style="text-align:right"><span class="status" style="color:${statusColor}">${statusLabel}</span></div>
    </div>
  </div>

  <h2>${L.item}</h2>
  <table>
    <thead>
      <tr>
        <th class="l">${L.item}</th><th>${L.opening}</th><th>${L.added}</th><th>${L.total}</th>
        <th>${L.closing}</th><th>${L.sold}</th><th>${L.price}</th><th>${L.amount}</th><th>${L.profit}</th>
      </tr>
    </thead>
    <tbody>
      ${body}
      <tr class="cat"><td colspan="7" style="text-align:right">${L.grand}</td><td class="n b">${money(expected)}</td><td class="n b">${money(gross)}</td></tr>
    </tbody>
  </table>

  <div class="two">
    <div>
      <h2>${L.summary}</h2>
      <table class="sum">
        ${summary.map(([k, v, c]) => `<tr><th>${k}</th><td${c ? ` style="color:${c}"` : ''}>${v}</td></tr>`).join('')}
      </table>
    </div>
    <div>
      <h2>${L.deductions}</h2>
      <table>${deductionRows}</table>
    </div>
  </div>

  ${session.reason ? `<div class="note"><strong>${L.reason}:</strong> ${esc(session.reason)}${session.note ? ` — ${esc(session.note)}` : ''}</div>` : ''}
  ${session.owner_comments ? `<div class="note"><strong>${L.ownerComments}:</strong> ${esc(session.owner_comments)}</div>` : ''}

  <div class="who">
    <div>${L.submittedBy}: <strong>${esc(session.submitted_by_name || '—')}</strong></div>
    <div>${L.approvedBy}: <strong>${esc(session.approved_by_name || '—')}</strong></div>
  </div>

  <div class="foot">
    <span>${L.footer} — ${SLOGAN[lang]}</span>
    <span>${esc(business.name)} · ${session.session_date}</span>
  </div>
</body>
</html>`;
}

export function openSessionReport(opts: Parameters<typeof buildSessionReportHtml>[0]): boolean {
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(buildSessionReportHtml(opts));
  w.document.close();
  return true;
}
