// The paper stock sheet: a print-ready A4 page a bar prints at the start of a
// shift and fills in by hand at closing. Only the item name and its price are
// printed — every counting column is deliberately left blank so the person
// closing writes the real numbers in, then keys them into Bermi afterwards.

import { groupByCategory } from './calc';
import type { Business, Lang, Product } from './types';
import { countryByCode } from './countries';

const SLOGAN: Record<Lang, string> = {
  en: 'Your business. One system.',
  sw: 'Biashara yako. Mfumo mmoja.',
};

interface SheetLabels {
  title: string;
  counter: string;
  date: string;
  shift: string;
  item: string;
  opening: string;
  added: string;
  total: string;
  sold: string;
  remain: string;
  price: string;
  amount: string;
  categoryTotal: string;
  grandTotal: string;
  totalSold: string;
  expenses: string;
  cash: string;
  mobile: string;
  bank: string;
  debt: string;
  countedBy: string;
  checkedBy: string;
  footer: string;
}

const LABELS: Record<Lang, SheetLabels> = {
  en: {
    title: 'DAILY STOCK SHEET',
    counter: 'Counter',
    date: 'Date',
    shift: 'Shift',
    item: 'Item',
    opening: 'Opening',
    added: 'Added',
    total: 'Total stock',
    sold: 'Sold',
    remain: 'Remain',
    price: 'Price',
    amount: 'Amount sold',
    categoryTotal: 'Subtotal',
    grandTotal: 'TOTAL',
    totalSold: 'Total sales',
    expenses: 'Expenses paid out',
    cash: 'Cash received',
    mobile: 'Mobile money received',
    bank: 'Bank / deposit',
    debt: 'Staff debt',
    countedBy: 'Counted by',
    checkedBy: 'Checked by',
    footer: 'Generated by Bermi One',
  },
  sw: {
    title: 'KARATASI YA BIDHAA YA SIKU',
    counter: 'Kaunta',
    date: 'Tarehe',
    shift: 'Zamu',
    item: 'Bidhaa',
    opening: 'Mwanzo',
    added: 'Imeongezwa',
    total: 'Jumla ya bidhaa',
    sold: 'Zimeuzwa',
    remain: 'Zilizobaki',
    price: 'Bei',
    amount: 'Kiasi cha mauzo',
    categoryTotal: 'Jumla ndogo',
    grandTotal: 'JUMLA',
    totalSold: 'Jumla ya mauzo',
    expenses: 'Matumizi yaliyolipwa',
    cash: 'Taslimu iliyopokelewa',
    mobile: 'Simu iliyopokelewa',
    bank: 'Benki / amana',
    debt: 'Deni la mfanyakazi',
    countedBy: 'Amehesabu',
    checkedBy: 'Amekagua',
    footer: 'Imetengenezwa na Bermi One',
  },
};

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function money(n: number, sym: string): string {
  return sym + ' ' + Math.round(n).toLocaleString('en-US');
}

export function buildStockSheetHtml(opts: {
  business: Business;
  products: Product[];
  lang: Lang;
  counterName?: string;
}): string {
  const { business, products, lang, counterName = '' } = opts;
  const T = LABELS[lang];
  const sym = countryByCode(business.country_code || 'TZ').sym;
  const groups = groupByCategory(products);
  const dateStr = new Date().toLocaleDateString(lang === 'sw' ? 'sw-TZ' : 'en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });

  const blank = '<td class="fill"></td>';

  const body = groups
    .map((g) => {
      const rows = g.items
        .map(
          (p) => `<tr>
        <td class="item">${esc(p.name)}<span class="unit">${esc(p.unit)}</span></td>
        ${blank}${blank}${blank}${blank}${blank}
        <td class="price">${money(p.price, sym)}</td>
        ${blank}
      </tr>`,
        )
        .join('');
      return `<tr class="cat"><td colspan="8">${esc(g.cat.toUpperCase())} <span class="catcount">${g.items.length}</span></td></tr>
      ${rows}
      <tr class="sub"><td colspan="7">${T.categoryTotal} — ${esc(g.cat)}</td><td class="fill"></td></tr>`;
    })
    .join('');

  const summaryRows = [T.totalSold, T.expenses, T.cash, T.mobile, T.bank, T.debt]
    .map((label) => `<tr><th>${label}</th><td class="fill"></td></tr>`)
    .join('');

  return `<!doctype html>
<html lang="${lang}">
<head>
<meta charset="utf-8" />
<title>${esc(business.name)} — ${T.title}</title>
<style>
  @page { size: A4 portrait; margin: 12mm 10mm; }
  * { box-sizing: border-box; }
  body { font-family: "Helvetica Neue", Arial, sans-serif; color: #111; margin: 0; font-size: 10.5px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #111; padding-bottom: 8px; margin-bottom: 10px; }
  .biz { font-size: 17px; font-weight: 800; letter-spacing: -0.2px; }
  .city { font-size: 10px; color: #555; margin-top: 2px; }
  .sheet { font-size: 12px; font-weight: 700; text-align: right; letter-spacing: 0.5px; }
  .meta { display: flex; gap: 14px; margin-bottom: 10px; }
  .meta div { flex: 1; font-size: 10px; color: #444; }
  .meta .line { border-bottom: 1px solid #999; height: 17px; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #bbb; padding: 3px 5px; }
  thead th { background: #f0f0f2; font-size: 9px; text-transform: uppercase; letter-spacing: 0.3px; text-align: center; padding: 5px 3px; }
  thead th.l { text-align: left; }
  td.item { font-weight: 600; }
  td.item .unit { color: #777; font-weight: 400; font-size: 9px; margin-left: 5px; }
  td.price { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
  td.fill { background: #fff; height: 19px; }
  tr.cat td { background: #e8e8ee; font-weight: 800; font-size: 9.5px; letter-spacing: 0.6px; padding: 4px 6px; }
  tr.cat .catcount { color: #666; font-weight: 600; margin-left: 6px; }
  tr.sub td { background: #fafafa; font-size: 9px; font-weight: 700; text-align: right; color: #444; }
  .totals { margin-top: 12px; width: 58%; }
  .totals th { text-align: left; background: #f0f0f2; font-size: 10px; font-weight: 700; width: 58%; }
  .totals td { height: 20px; }
  .sign { display: flex; gap: 30px; margin-top: 16px; }
  .sign div { flex: 1; font-size: 9.5px; color: #555; }
  .sign .line { border-bottom: 1px solid #999; height: 24px; }
  .foot { margin-top: 14px; border-top: 1px solid #ccc; padding-top: 6px; display: flex; justify-content: space-between; font-size: 9px; color: #777; }
  tr { page-break-inside: avoid; }
  @media print { .noprint { display: none; } }
  .noprint { margin-bottom: 12px; }
  .noprint button { font: inherit; font-weight: 700; padding: 8px 16px; border-radius: 8px; border: 1px solid #444; background: #111; color: #fff; cursor: pointer; }
</style>
</head>
<body>
  <div class="noprint"><button onclick="window.print()">Print / Save as PDF</button></div>

  <div class="head">
    <div>
      <div class="biz">${esc(business.name)}</div>
      <div class="city">${esc([business.city, dateStr].filter(Boolean).join(' · '))}</div>
    </div>
    <div class="sheet">${T.title}</div>
  </div>

  <div class="meta">
    <div>${T.counter}${counterName ? `: <strong>${esc(counterName)}</strong>` : ''}<div class="line"></div></div>
    <div>${T.date}<div class="line"></div></div>
    <div>${T.shift}<div class="line"></div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th class="l">${T.item}</th>
        <th>${T.opening}</th>
        <th>${T.added}</th>
        <th>${T.total}</th>
        <th>${T.sold}</th>
        <th>${T.remain}</th>
        <th>${T.price}</th>
        <th>${T.amount}</th>
      </tr>
    </thead>
    <tbody>
      ${body}
      <tr class="cat"><td colspan="7" style="text-align:right">${T.grandTotal}</td><td class="fill"></td></tr>
    </tbody>
  </table>

  <table class="totals">
    ${summaryRows}
  </table>

  <div class="sign">
    <div>${T.countedBy}<div class="line"></div></div>
    <div>${T.checkedBy}<div class="line"></div></div>
  </div>

  <div class="foot">
    <span>${T.footer} — ${SLOGAN[lang]}</span>
    <span>${esc(business.name)} · ${dateStr}</span>
  </div>
</body>
</html>`;
}

/** Opens the sheet in a new tab so the user can print it or save it as a PDF. */
export function openStockSheet(opts: Parameters<typeof buildStockSheetHtml>[0]): boolean {
  const html = buildStockSheetHtml(opts);
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  return true;
}
