// Generated by vo.py — the picture is cut to these times.
window.VO = [
 {
  "id": 1,
  "start": 0.7,
  "dur": 4.198,
  "text": "Every night, your business tells a story. Most owners never get to hear it."
 },
 {
  "id": 2,
  "start": 6.4,
  "dur": 4.589,
  "text": "Bottles counted on paper. Cash in a drawer. Numbers you just have to trust."
 },
 {
  "id": 3,
  "start": 12.4,
  "dur": 1.202,
  "text": "Meet Bermi One."
 },
 {
  "id": 4,
  "start": 15.2,
  "dur": 2.387,
  "text": "Your staff sign in with their own PIN."
 },
 {
  "id": 5,
  "start": 18.4,
  "dur": 5.027,
  "text": "Every bottle, every category, live. And Bermi warns you before anything runs out."
 },
 {
  "id": 6,
  "start": 25.2,
  "dur": 2.188,
  "text": "At closing time, they count the shelves."
 },
 {
  "id": 7,
  "start": 28.4,
  "dur": 5.339,
  "text": "Bermi does the maths. What sold, what it earned, and exactly what cash should be in the drawer."
 },
 {
  "id": 8,
  "start": 36.2,
  "dur": 3.082,
  "text": "Cash, mobile money, expenses, even staff debts."
 },
 {
  "id": 9,
  "start": 40.0,
  "dur": 1.675,
  "text": "Everything is accounted for."
 },
 {
  "id": 10,
  "start": 43.0,
  "dur": 2.166,
  "text": "Then it's on your phone, wherever you are."
 },
 {
  "id": 11,
  "start": 46.4,
  "dur": 1.59,
  "text": "One tap. Verified."
 },
 {
  "id": 12,
  "start": 49.0,
  "dur": 1.771,
  "text": "Tomorrow starts already counted."
 },
 {
  "id": 13,
  "start": 52.6,
  "dur": 1.689,
  "text": "Your cash book writes itself."
 },
 {
  "id": 14,
  "start": 55.4,
  "dur": 1.692,
  "text": "Reports are ready for WhatsApp."
 },
 {
  "id": 15,
  "start": 58.2,
  "dur": 2.413,
  "text": "And when you have a question, just ask Bermi."
 },
 {
  "id": 16,
  "start": 62.2,
  "dur": 3.113,
  "text": "One branch, or ten. English, or Kiswahili."
 },
 {
  "id": 17,
  "start": 66.2,
  "dur": 3.549,
  "text": "Pay monthly, quarterly or yearly, straight from mobile money."
 },
 {
  "id": 18,
  "start": 71.2,
  "dur": 0.961,
  "text": "Bermi One."
 },
 {
  "id": 19,
  "start": 73.6,
  "dur": 2.599,
  "text": "Every bottle. Every shilling. Every night."
 },
 {
  "id": 20,
  "start": 78.4,
  "dur": 2.101,
  "text": "Run your business as one system."
 },
 {
  "id": 21,
  "start": 83.0,
  "dur": 1.799,
  "text": "Try it free for fourteen days."
 }
];
